spring.application.name=firstProject
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercejava
spring.datasource.username=postgres
spring.datasource.password=chamrern
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/